### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [3, 16, 5, 5]] is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

### ISSUE THREAD

**Issue by renato-rodrig** [mtics/deep-photo-enhancer#9]
![Captura de tela de 2021-04-09 12-29-05](https://user-images.githubusercontent.com/57590842/114204243-58f69600-992f-11eb-9655-7f92acf23330.png)

**Comment by mtics** [comment]
Please try one of the following:
1. Set all `inplace=True` to `False`, or
2. Change all operations like `a+=b` to `a=a+b`, or
3. Check your pytorch's version, which is `1.3.1` in my repo.

**Comment by renato-rodrig** [comment]
Hello my friend, I was using a more updated version of pytorch. His third suggestion worked. Thank you for your help!
